### ISSUE TITLE
I couldn't deploy: cdk deploy

### ISSUE THREAD

**Issue by Gambo019** [awslabs/genai-bedrock-agent-chatbot#12]
![bedrock_error](https://github.com/user-attachments/assets/8bc20abb-5ec1-4c84-977b-9a5895b51163)

I've been stuck in this state for almost an hour and the deployment is stopped midway because the authentication token of requests has expired. I've tried it several times but the result is the same.

I am using python 3.11.8.

I would like to know how to deploy it successfully.

**Comment by praveenflash** [comment]
Can you check the ECS logs for the issue?

**Comment by Gambo019** [comment]
I checked logs and I found "exec /usr/local/bin/streamlit: exec format error".
And I noticed that there are 2 versions of python in your codebase.

`code/lambdas/action-lambda/Dockerfile --> FROM public.ecr.aws/lambda/python:3.11@sha256:58834a0d4d7f86326b6c91d516c66fbe8e91ccd3646ceba4025a66a7a8906e81`

```
code_stack.py -->

self.lambda_runtime = lambda_.Runtime.PYTHON_3_12

def create_lambda_layer(self, layer_name: str) -> lambda_.LayerVersion:
        layer_code_path = path.join(os.getcwd(), self.LAYERS_SOURCE_FOLDER, layer_name)

        layer = lambda_.LayerVersion(
            self,
            layer_name,
            code=lambda_.Code.from_asset(
                layer_code_path,
                bundling=BundlingOptions(
                    image=DockerImage.from_registry(
                        "public.ecr.aws/sam/build-python3.12"
                    ),
                    command=[
                        "bash",
                        "-c",
                        f"""
                        # Create the required directory structure
                        mkdir -p /asset-output/python/lib/python3.12/site-packages
                        
                        # Install requirements to the correct directory
                        pip install \
                            --platform manylinux2014_aarch64 \
                            --implementation cp \
                            --python-version 3.12 \
                            --only-binary=:all: \
                            --target /asset-output/python/lib/python3.12/site-packages \
                            -r requirements.txt
                        """,
                    ],
                ),
            ),
            compatible_runtimes=[self.lambda_runtime],
            compatible_architectures=[lambda_.Architecture.ARM_64],
            description=f"Lambda layer for {layer_name}",
            layer_version_name=layer_name,
        )

        return layer
```

`code/streamlist-app/Dockerfile --> FROM python:3.12`

Actually, I replaced 3.12 with 3.11 in code_stack.py to solve this problem. But I kept the version in `code/streamlist-app/Dockerfile`.

Because I am not an expert in AWS, I hope your help.

**Comment by praveenflash** [comment]
Seems you are building the code on a completely different platform. You will need `docker buildx` command to build the layers and container images. Please try to build the code with `docker buildx` command installed and ready to use or build the application on aarch64 platform.

More details of this issue here : https://stackoverflow.com/questions/73285601/docker-exec-usr-bin-sh-exec-format-error

**Comment by tronar** [comment]
Well, the issue is not resolved. I deployed all this in a fresh awslinux2003 t3.medium and got this issue, and nowhere in the requirements says origin architecture should be ARM.
Can you please explain how to modify the project to use buildx to force ARM arch in the images ?

**Comment by praveenflash** [comment]
You can follow the below [repo](https://github.com/docker/buildx) to get `buildx` activated in your environment. Once it is enabled, CDK should take care of using it to build for the target architecture.

**Comment by tronar** [comment]
Thanks
