### ISSUE TITLE
exec_code error

### ISSUE THREAD

**Issue by tronar** [awslabs/genai-bedrock-agent-chatbot#13]
After deploying using a T4g origin, I got the system working but a sample question rendered an error.
Q: What is a target use case for a P4 instance ?

KeyError: 'source'
Traceback:
File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
File "/app/app.py", line 162, in <module>
    main()
File "/app/app.py", line 156, in main
    show_message()
File "/app/app.py", line 127, in show_message
    source_title = "\n\n **Source**:" + "\n\n" + response_output["source"]
                                                 ~~~~~~~~~~~~~~~^^^^^^^^^^

**Comment by jundongq** [comment]
Hi @tronar , can you check the lambda log to see what is the outcome for this question?

**Comment by tronar** [comment]
The problem stems from a frequency check, i.e., the system is making somehow too many calls to the model, which is weird as that was my second "question". But I don't understand so far the whole arquitecture, many lambdas and parts that I don't know where to start peeling.  I rested and after a while it answered again, but I fail to understand how did I trigger a rate limiter.

Would you happen to have some form of description of workflows ?
Also, I tried to see if I could insert a guardrail in the loop, but I was not able to pinpoint where the model is instantiated.
May be you can help ?

**Comment by jundongq** [comment]
It is likely that your aws account has limit quota for the Claude model invocation.

You can do the following: 
1. Open the Amazon CloudWatch Log, create a log group for logging model invocations
2. Open the Amazon Bedrock, under the "Bedrock configurations/Settings", enable "Model invocation logging", under the "Log group name", put the newly created log group.

Use the logging, you can see how many LLM calls are triggered during the process.
