### ISSUE TITLE
cdk destroy does not remove knowledge base

### ISSUE THREAD

**Issue by nicholsn** [awslabs/genai-bedrock-agent-chatbot#5]
When I run `cdk destroy` the stack appears to be effectively destroyed, however the knowledge base fails to be removed. This causes subsequent deployments to fail because an existing resource with the same name is left behind. 

The workaround for removing the knowledge base is to edit the settings for the data source and label the `Data deletion policy` as `Retain` rather than `Delete`.

Any idea why this is needed?

**Comment by praveenflash** [comment]
Thanks for the suggestion! We will update the code and test it with the configuration
